# Generated by Django 5.1.4 on 2024-12-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellidoP', models.CharField(max_length=15)),
                ('apellidoM', models.CharField(max_length=15)),
                ('Correo', models.CharField(max_length=60, unique=True)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
