# Generated by Django 5.1.4 on 2024-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
